import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar configuration for Physical AI & Humanoid Robotics textbook.
 * Auto-generates sidebar from the docs folder structure (X.Y.Z chapter numbering).
 * Category metadata is defined in _category_.json files in each chapter folder.
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from docs folder structure
  bookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
